apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: myapp-bleu
  namespace: production
spec:
  containers:
  - name: webapp-color
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env
      - name: APP_COLOR
        value: bleu
