apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-web
  name: service-pod-web
  namespace: production
spec:
  ports:
    - name: 30008:8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: web
  type: NodePort
