apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tp4
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql-volume
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-claim
  env:
    - name: MYSQL_DATABASE
      value: eazytraining
    - name: MYSQL_USER
      value: eazy
    - name: MYSQL_PASSWORD
      value: eazy
    - name: MYSQL_ROOT_PASSWORD
      value: password
